name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:  # ✅ เพิ่ม manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t asia-southeast1-docker.pkg.dev/causal-relic-457214-g5/kts-mini-dashboard-backend/kts-mini-dashboard-backend .

      - name: Push Docker image to Artifact Registry
        run: docker push asia-southeast1-docker.pkg.dev/causal-relic-457214-g5/kts-mini-dashboard-backend/kts-mini-dashboard-backend

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: kts-mini-dashboard-backend
          region: asia-southeast1
          image: asia-southeast1-docker.pkg.dev/causal-relic-457214-g5/kts-mini-dashboard-backend/kts-mini-dashboard-backend
